### PR TITLE
Rework materialcolor

### PR DESCRIPTION
**Pull request by fistak**
image

Improve MaterialColor mod:
- refactor greatly
- allow for brighter colors
- simplify config
  - get rid of building offset config
  - use colors from oni for not configured elements

~~Added two universal color modificators for easy tuning.~~

image

Not compatible with previous config files.

### CODE REVIEW

**Comment by fistak** [comment]
Hold up with the merge, I need to fix some major issue.

**Comment by javisar** [comment]
Very nice rework @fistak, I have to try it. Just one question for now, why did you remove TemperatureOverlay mod? It was working I think. Probably we should make a separate mod for it.

**Comment by fistak** [comment]
Thanks @javisar ;D `TemperatureOverlay` definitely doesn't belong here. I'm going to extract it to separate mod after I'm done with this.

**Comment by javisar** [comment]
I've merged this PR to the master branch. Nice job. Before that, I've extracted Temperature Overlay from Material color and I've created a new mod for it.
Thank you.

**Pull request merged**
