### PR TITLE
Two new mods: Pipe Pressure Sensor and Temperature Filter

### PR DESCRIPTION
**Pull request by Blindfold**
As a part of my Feature request in Modloader repo (https://github.com/javisar/ONI-Modloader/issues/40) I proposing two new mods:
**FluidPressureSensor**
These are logic sensors for gas and liquid pipes which are triggered when pipe contains certain mass of gas or liquid. I suppose it will mostly be used with "when above 0" condition so it will trigger whenever any element run through it's pipe.

**TemperatureFilter**
Acts like a normal gas/liquid filter but instead of sorting flow by elements it will sort it by temperature of pipe's contents. When element in the input cell reach defined temperature threshold it will be redirected to the orange output, otherwise it will be dumped into the default output (green).

### CODE REVIEW

**Comment by Sijko** [comment]
как ползунок значений "знает" какой параметр объекта менять?

**Comment by rainbowdesign** [comment]
I would take them into exiting world mod.

**Comment by rainbowdesign** [comment]
@Blindfold are you in discord?

**Comment by Blindfold** [comment]
> @Blindfold are you in discord?

Yes I am. What channel do you want me in?

**Comment by Sijko** [comment]
> > @Blindfold are you in discord?
> 
> Yes I am. What channel do you want me in?

DarthNihilus#4649 Маякни мне плз, вдруг мне понадобится твой совет.

**Comment by rainbowdesign** [comment]
you could add me. rainbow#7028

**Comment by Blindfold** [comment]
> I don't mind also to host these mods, it'd be a honor, but my time is limited and I fear to not be able to keep maintaining everything. I strongly suggest that @Blindfold, you can have your how mod repo. Your updates and mods are very good :)

@javisar, thank you for your appreciation. Your point makes sense. Especially considering the fact that I do plan to make mode MODs, which I feel will be quite  useful. I'll arrange a separate repo for these stuff. 
Special thanks for your FluidWarp mod. It's THE most useful mod I've seen so far. =)

**Comment by Blindfold** [comment]
Ok, these two mods can be found in my repo https://github.com/Blindfold-Games/ONI-Blind-MODS from nowon. It's not polished, no binary releases yet, but I'm working on it.
@javisar feel free to reject the PR.

**Comment by javisar** [comment]
Yeah, FluidWarp was mostly a prototype, without your rework it'd still be broken.
Nice to see your new repo. I'll add it to the list of community mods if you don't mind [here](https://github.com/javisar/ONI-Modloader#mods-based-in-harmony) and in the forums
I close the PR. Thanks

**Pull request closed without merging**
