### PR TITLE
Added seperated aggregator

### PR DESCRIPTION
**Pull request by rainbowdesign**

### CODE REVIEW

**Comment by rainbowdesign** [comment]
> I'd prefer to read the files in json independently

I dont know how json work i never used it. So thats likely beyond my skills. If you really want to do this only on the json level you will have to write it.
I added a line to purge duplicates by filename and i separated the code to its own file.

**Comment by javisar** [comment]
I appreciate your changes but:
- Have you tried to compile and test it? The code doesn't even compile. With a PR, I will expect a kind of working version.
- If you make a Pull Request it's better to make before the PR an Update from master to syncronize with the latest version.

I've made a rework and it seems to work. At least as a first version. Have a look to the last commit in this PR.
Please, if you can, test it a little bit and I will merge it to the master branch. 

Changes in BuildingModifier and ONI-Common:
https://github.com/rainbowdesign/ONI-Modloader-Mods/tree/b47e950aacf91f171539cbd1c6ca0ac8ee96b9a7/Mods/

Check the howto file for more info.

Example output:

> [ INFO  ] [12/19/2018, 17:05:02.9611980] Loading: Mods\BuildingModifier\Config\BuildingModifierState.json
[ INFO  ] [12/19/2018, 17:05:02.9727140] Loading: Mods\BuildingModifier\Config\Modifiers\Batteries.json
[ INFO  ] [12/19/2018, 17:05:02.9842446] Loading: Mods\BuildingModifier\Config\Modifiers\Canvas.json
[ INFO  ] [12/19/2018, 17:05:02.9847464] Loading: Mods\BuildingModifier\Config\Modifiers\Doors.json
[ INFO  ] [12/19/2018, 17:05:02.9852473] Loading: Mods\BuildingModifier\Config\Modifiers\Generators.json
[ INFO  ] [12/19/2018, 17:05:02.9852473] Loading: Mods\BuildingModifier\Config\Modifiers\MoreMaterials.json
[ INFO  ] [12/19/2018, 17:05:02.9872517] Loading: Mods\BuildingModifier\Config\Modifiers\Reservoirs.json
[ INFO  ] [12/19/2018, 17:05:02.9887557] Loading: Mods\BuildingModifier\Config\Modifiers\Sensors.json
[ INFO  ] [12/19/2018, 17:05:02.9902597] Loading: Mods\BuildingModifier\Config\Modifiers\Storage.json
[ INFO  ] [12/19/2018, 17:05:02.9912624] Loading: Mods\BuildingModifier\Config\Modifiers\Vents.json

Thank you @rainbowdesign

**Comment by rainbowdesign** [comment]
I did not test it essentially because i dont know json and i think i cannot test if its working. And also i wanted you to adapt it anyways so you will get to know it by testing ;)

**Comment by rainbowdesign** [comment]
Also the aggregator is likely very versions independent.

**Comment by javisar** [comment]
I've merged this PR to master branch.

**Pull request merged**
