### PR TITLE
Add FreeCameraMod

### PR DESCRIPTION
**Pull request by fistak**
Adds feature requested by [NitroTurtle] through @javisar (I hope I got that right) at #90: Allow camera to move past map borders. I have added this functionality as a new mod instead of adding it to the `CameraControllerMod` so it can be toggled easily.

This is probably the simplest mod ever made :D

### CODE REVIEW

**Comment by javisar** [comment]
Thanks for the fix. Are you willing to move this addition to the CameraController mod? Seems to fit there.

**Comment by fistak** [comment]
Well, I was thinking about leaving it as a separate mod, so it can be toggled at will, but it's up to you to decide.

**Comment by javisar** [comment]
I moved your fix to CameraController mod, also added a config file (ONI-Common required). Let me know what do you think.

**Comment by fistak** [comment]
Of course it looks perfectly fine how you added it, but it really seems counter-productive to change two separate mods to one with config, which probably nobody will ever configure.

Maybe its about finding a proper names for both mods, for example keep it simple and call them something like `ExpandCameraZoom` and `OffBoundsCamera`?

**Comment by javisar** [comment]
To be honest, I don't want to maintain another mod, I prefer to integrate them into one since it can include all the camera functionality in one place. For example, I had various mods that changed some building properties and I integrated them into one, aka BuildingModifier.
If the people are not willing to modify a config file, then maybe they shouldn't use mods, at least for now. Just an opinion.
If despite this, you want to keep the mods separated, you could keep and maintain it in your git, no worries.

**Comment by fistak** [comment]
Maybe I'm wrong, but for me it looks like actually maintaining another mod is slightly less effort than maintaining combined one.

For example if this small mod ever breaks - people can still use extended camera zoom in the other mod, which is much more important feature.

These are just my 2 cents, I guess I'll have accept your approach ;)

Merge whenever you want.

**Comment by javisar** [comment]
Thank you for the contribution @fistak. Very appreciated.

**Pull request merged**
