### PR TITLE
Add MaterialColor filtering

### PR DESCRIPTION
**Pull request by fistak**
Requested by @cairath and Mahskie#0001@discord

Allows to apply `MaterialColor` to only some building types, or apply it to all but some building types.

It's all managed from `MaterialColor/Config/MaterialColorState.json` file. Default (apply to everything):
```
{
  ...

  "TypeFilterInfo": {
    "Inclusive": false,
    "Rules": []
  }
}
```
If `Inclusive` is set to `false` - ALL buildings EXCEPT those listed in the `Rules` will be colored. For example here everything but the `HeadQuarters`(PrintingPod) will be tinted:
```
{
  ...

  "TypeFilterInfo": {
    "Inclusive": false,
    "Rules": [
      "HeadQuarters"
    ]
  }
}
```
If `Inclusive` is set to `true` - ONLY buildings listed in the `Rules` will be colored. For example here only `HeadQuarters`(PrintingPod) will tinted:
```
{
  ...

  "TypeFilterInfo": {
    "Inclusive": true,
    "Rules": [
      "HeadQuarters"
    ]
  }
}
```
Rules are case-sensitive but partial matches suffice. For example this is basically the same behaviour as above, unless there's other building with name that contains `Head` string:
```
{
  ...

  "TypeFilterInfo": {
    "Inclusive": true,
    "Rules": [
      "Head"
    ]
  }
}
```
Example of only printing pod colored:

image

Someone please review the code at least briefly if it makes sense and works.

### CODE REVIEW

**Comment by javisar** [comment]
Works perfect for me. Thank you very much. I just added a config option to match the exact building id. If you agree i'll merge the pull request.

**Comment by javisar** [comment]
I added the exact match in order to allow the exclusion of only one building. For example if I want to exclude only the small battery, I have to add "Battery" to the list, but then all kinds of battery are excluded.

**Comment by fistak** [comment]
Okay I get it - when big battery is called `Battery` and small battery is called `SmallBattery`, excluding `Battery` without touching the other one is the issue.

As I said before - I'm okay with the merge here.

**Comment by javisar** [comment]
Thank you for the contribution @fistak

**Pull request merged**
