### PR TITLE
Revert to old gas color calculation and improve on it

### PR DESCRIPTION
**Pull request by fistak**
I've made some improvements for gas overlay mod. It was made first with @Killface1980's mod loader fork in mind, but I think this is a more appropriate place.

@javisar Thanks for making the mod loader and @Killface1980 for keeping my mods up to date and compatible with it ;)

@Killface1980 using HSV colors for gas overlay manipulation was great idea, but I think the old algorithm with a few changes that I made looks much better (it still uses HSV colors).

Some random example:

example

Also I have added special case for Carbon Dioxide as giving more saturation to it was unnoticeable.

Carbon Dioxide comparison at 2500g to 100g pressure:

- Vanilla:

vanilla co2 2500-100g

- @Killface1980:

old co2 2500-100g

- Mine:

new co2 2500-100g

### CODE REVIEW

**Comment by Killface1980** [comment]
I like the new colors, looks great. I was trying to make high/ear pop pressure more visible, but I shouldn't change the hue too much, as steam might look like highly pressurized oxygen.

**Comment by fistak** [comment]
@Killface1980 Thanks! Yeah some gases looked very odd. Maybe a slight change in hue can be helpful, we can still get back to it ;) Have you tried the mod in-game already?

**Comment by javisar** [comment]
@fistak @Killface1980 I also like the colors. If everyone agrees I will try to merge the pull but I see a couple of things that can be improved.
Is there a way to keep "Pop ear drum marker"? I think that could be interesting to maintain it.
What about to add a new property to MaterialColorState.json with the gas color mode you want? We could let the user to choose which mode he wants.

What do you think?

**Comment by fistak** [comment]
@javisar The problem with the earlier "Pop ear drum marker" was that it wasn't really what it was called. It was simply a change of gas coloring past a pressure point. Kind of extension of the colors beyond the range, that everyone already could configure to their own needs in MaterialColorState.json.

Old algorithm for comparison (pressure diagonally from 7kg to 100g):

image

Its really hard to tell where is the mark. It would be even harder if it would be across several rooms and with buildings obscuring the view.

I think I have fixed it though. A flat hue value is added to the gas color when it breaks ear pop pressure threshold. Example of the same 7kg to 100g diagonally:

image

You can clearly see where ear pop happens, BTW its 5kg not 2.5kg. I think the change should be more subtle for me, but I'm not the fan of this feature anyway so don't mind me ;)

I didn't test every gas yet, but most common ones looks okay.

@Killface1980 I don't want to blame you how you implemented this feature, sorry if it looks like that for you :P I could actually improve a lot thanks to your changes.

Carbon Dioxide is still not really affected by the marker, because it's black, but I think I can work something out about it.

@javisar About making the whole ear drum pop marker feature optional - of course this would be the best, the issue is if it should be enabled or disabled by default.

**Comment by fistak** [comment]
image

I think this looks fine now (ear popping carbon dioxide). Color might need some tuning.

**Comment by javisar** [comment]
Neat change @fistak. 
Next step probably I'll move the config file to the real mod (https://github.com/javisar/ONI-Modloader-Mods/issues/4)

**Pull request merged**
